// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sport_app_backend.Data;

#nullable disable

namespace sport_app_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260812125526_addLastSenderUserIdToConversations")]
    partial class addLastSenderUserIdToConversations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("sport_app_backend.Models.Account.Athlete.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ActiveWorkoutProgramId")
                        .HasColumnType("int");

                    b.Property<double>("CurrentWeight")
                        .HasColumnType("double");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<int>("RestTime")
                        .HasColumnType("int");

                    b.Property<int>("TimeBeforeWorkout")
                        .HasColumnType("int");

                    b.Property<int>("TotalActivities")
                        .HasColumnType("int");

                    b.Property<double>("TotalCalories")
                        .HasColumnType("double");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("WeightGoal")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ActiveWorkoutProgramId");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Athlete.WeightEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("date");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("WeightEntries");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Coach.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<string>("BaleUserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("CoachQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("EitaaUserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("InstagramLink")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<double>("ServiceFee")
                        .HasColumnType("double");

                    b.Property<bool>("ShowWebsite")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SiteDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Slogan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelegramLink")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("Verified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("WebSiteUrl")
                        .HasMaxLength(51)
                        .HasColumnType("varchar(51)");

                    b.Property<DateTime>("WebSiteUrlUpDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("WhatsApp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CoachQuestionId");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Coach.CoachCardNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("ShebaNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId")
                        .IsUnique();

                    b.ToTable("CoachCardNumbers");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AthleteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageProfile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastLoginSite")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastSeenApp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SiteRefreshToken")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TypeOfUser")
                        .HasColumnType("int");

                    b.Property<bool>("UserIsBan")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId")
                        .IsUnique();

                    b.HasIndex("CoachId")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RefreshToken")
                        .HasDatabaseName("IX_User_RefreshToken");

                    b.HasIndex("SiteRefreshToken")
                        .HasDatabaseName("IX_User_SiteRefreshToken");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("sport_app_backend.Models.Actions.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActivityCategory")
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<double>("CaloriesLost")
                        .HasColumnType("double");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Distance")
                        .HasColumnType("double");

                    b.Property<double>("Duration")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("sport_app_backend.Models.Actions.CouchExercise.CoachPineExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BaseCategory")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("CoachPineExercises");
                });

            modelBuilder.Entity("sport_app_backend.Models.Actions.CouchExercise.LastWorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseIds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WorkoutProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("LastWorkoutExercises");
                });

            modelBuilder.Entity("sport_app_backend.Models.Actions.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BaseCategory")
                        .HasColumnType("int");

                    b.Property<int>("BaseMuscle")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<int>("Equipment")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseLevel")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("int");

                    b.Property<int>("ForceType")
                        .HasColumnType("int");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("varchar(170)");

                    b.Property<int>("Mechanics")
                        .HasColumnType("int");

                    b.Property<double>("Met")
                        .HasColumnType("double");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TargetMuscles")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VideoLink")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("sport_app_backend.Models.AthleteChangePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("AthleteChangePhotos");
                });

            modelBuilder.Entity("sport_app_backend.Models.AthleteFaq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AthleteFaq");
                });

            modelBuilder.Entity("sport_app_backend.Models.Challenge_Achievement.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("ChallengeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("sport_app_backend.Models.Chat.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SenderUserId");

                    b.HasIndex("ConversationId", "Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("sport_app_backend.Models.Chat.Conversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LastMessageSenderId")
                        .HasColumnType("int");

                    b.Property<string>("LastMessageText")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LastMessageAt");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("sport_app_backend.Models.Chat.ConversationParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("LastReadMessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ConversationId", "UserId")
                        .IsUnique();

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("sport_app_backend.Models.CoachFaq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CoachFaq");
                });

            modelBuilder.Entity("sport_app_backend.Models.CoachQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("DifficultTrackAthletes")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Disciplines")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("HardCommunicationWithAthletes")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("ManagingRevenue")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Motivations")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PresentsPracticeProgram")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TrackAthlete")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("WorkOnlineWithAthletes")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CoachQuestions");
                });

            modelBuilder.Entity("sport_app_backend.Models.InAppMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ActionLink")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ActionText")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("TargetRole")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("InAppMessages");
                });

            modelBuilder.Entity("sport_app_backend.Models.Login_Sinup.CodeVerify", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("TimeCodeSend")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CodeVerifies");
                });

            modelBuilder.Entity("sport_app_backend.Models.NotificationSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastTrainingReminderSentAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("P256DH")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationSubscriptions");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.CoachPayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Imagelink")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("CoachPayouts");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.DiscountCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AppliesToAllServices")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DiscountCodes");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.DiscountCodeCoachService", b =>
                {
                    b.Property<int>("DiscountCodeId")
                        .HasColumnType("int");

                    b.Property<int>("CoachServiceId")
                        .HasColumnType("int");

                    b.HasKey("DiscountCodeId", "CoachServiceId");

                    b.HasIndex("CoachServiceId");

                    b.ToTable("DiscountCodeCoachServices");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<double>("AppFee")
                        .HasColumnType("double");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int?>("AthleteQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("CoachServiceId")
                        .HasColumnType("int");

                    b.Property<double>("CodeDiscountAmount")
                        .HasColumnType("double");

                    b.Property<int?>("DiscountCodeId")
                        .HasColumnType("int");

                    b.Property<double>("OriginalAmount")
                        .HasColumnType("double");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<long>("RefId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("AthleteQuestionId");

                    b.HasIndex("CoachId");

                    b.HasIndex("CoachServiceId");

                    b.HasIndex("DiscountCodeId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.PaymentAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("CoachServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("SmsIsSend")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.HasIndex("CoachServiceId");

                    b.ToTable("PaymentAttempts");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("longtext");

                    b.Property<int>("TransactionStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.ExerciseChangeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("Reason")
                        .HasColumnType("int");

                    b.Property<int>("SingleExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.HasIndex("SingleExerciseId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("ExerciseChangeRequests");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.ExerciseFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("NegativeReason")
                        .HasColumnType("int");

                    b.Property<int>("SingleExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.HasIndex("SingleExerciseId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("ExerciseFeedbacks");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.ProgramInDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ForWhichDay")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("ProgramInDays");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.SingleExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramInDayId")
                        .HasColumnType("int");

                    b.Property<int?>("RepType")
                        .HasColumnType("int");

                    b.Property<string>("RepsJson")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ProgramInDayId");

                    b.ToTable("SingleExercises");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("ExerciseCompletionBitmap")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("ExerciseFeeling")
                        .HasColumnType("int");

                    b.Property<int>("ProgramInDayId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingSessionStatus")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramInDayId");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("CompletedSessionCount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime?>("LastExerciseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramDuration")
                        .HasColumnType("int");

                    b.Property<int>("ProgramLevel")
                        .HasColumnType("int");

                    b.Property<int>("ProgramPriority")
                        .HasColumnType("int");

                    b.Property<bool>("RenewalReminderSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TotalSessionCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("WorkoutPrograms");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgramFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<string>("AthleteName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeedBack")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsChosen")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutProgramId")
                        .HasColumnType("int");

                    b.Property<string>("WorkoutProgramName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("WorkoutProgramId")
                        .IsUnique();

                    b.ToTable("WorkoutProgramFeedback");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgramTemplate.TemplateProgramInDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ForWhichDay")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutProgramTemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutProgramTemplateId");

                    b.ToTable("TemplateProgramInDays");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgramTemplate.TemplateSingleExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("RepType")
                        .HasColumnType("int");

                    b.Property<string>("RepsJson")
                        .HasColumnType("longtext");

                    b.Property<int>("TemplateProgramInDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TemplateProgramInDayId");

                    b.ToTable("TemplateSingleExercises");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgramTemplate.WorkoutProgramTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProgramDuration")
                        .HasColumnType("int");

                    b.Property<int>("ProgramLevel")
                        .HasColumnType("int");

                    b.Property<int>("ProgramPriority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("WorkoutProgramTemplates");
                });

            modelBuilder.Entity("sport_app_backend.Models.Question.A_Question.AthleteBodyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int?>("AthleteQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("BackLink")
                        .HasColumnType("longtext");

                    b.Property<string>("FrontLink")
                        .HasColumnType("longtext");

                    b.Property<string>("SideLink")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AthleteQuestionId")
                        .IsUnique();

                    b.ToTable("AthleteImage");
                });

            modelBuilder.Entity("sport_app_backend.Models.Question.A_Question.AthleteQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<string>("ComingCompetition")
                        .HasColumnType("longtext");

                    b.Property<string>("CompetitionHistory")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CurrentBodyForm")
                        .HasColumnType("int");

                    b.Property<string>("CurrentMedications")
                        .HasColumnType("longtext");

                    b.Property<int>("DaysPerWeekToExercise")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseGoal")
                        .HasColumnType("int");

                    b.Property<int>("ExerciseLocation")
                        .HasColumnType("int");

                    b.Property<int?>("FitnessLevel")
                        .HasColumnType("int");

                    b.Property<string>("NotesForCoach")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("SittingHour")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("AthleteQuestions");
                });

            modelBuilder.Entity("sport_app_backend.Models.Question.A_Question.InjuryArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("HormonalAndGlandular")
                        .HasColumnType("longtext");

                    b.Property<string>("InternalAndDigestive")
                        .HasColumnType("longtext");

                    b.Property<bool>("None")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Others")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Skeletal")
                        .HasColumnType("longtext");

                    b.Property<string>("SoftTissueAndLigament")
                        .HasColumnType("longtext");

                    b.Property<string>("Specific")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AthleteQuestionId")
                        .IsUnique();

                    b.ToTable("InjuryAreas");
                });

            modelBuilder.Entity("sport_app_backend.Models.Support.SupportTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("sport_app_backend.Models.Support.TicketMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsFromSupport")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SenderId")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketMessages");
                });

            modelBuilder.Entity("sport_app_backend.Models.TrainingPlan.CoachService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NumberOfSell")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("CoachServices");
                });

            modelBuilder.Entity("sport_app_backend.Models.UserExternalAccount.EitaaLoginSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EitaaUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EitaaUsername")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("EitaaLoginSessions");
                });

            modelBuilder.Entity("sport_app_backend.Models.UserExternalAccount.UserExternalAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProviderUsername")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("UserExternalAccounts");
                });

            modelBuilder.Entity("sport_app_backend.Models.UserMessageStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("InAppMessageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InAppMessageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMessageStatuses");
                });

            modelBuilder.Entity("sport_app_backend.Models.WaterInDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("NumberOfCupsDrinked")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("WaterInDays");
                });

            modelBuilder.Entity("sport_app_backend.Models.WaterInTake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("DailyCupOfWater")
                        .HasColumnType("int");

                    b.Property<int>("Reminder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId")
                        .IsUnique();

                    b.ToTable("WaterInTakes");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Athlete.Athlete", b =>
                {
                    b.HasOne("sport_app_backend.Models.Program.WorkoutProgram", "ActiveWorkoutProgram")
                        .WithMany()
                        .HasForeignKey("ActiveWorkoutProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActiveWorkoutProgram");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Athlete.WeightEntry", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithMany("WeightEntries")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Coach.Coach", b =>
                {
                    b.HasOne("sport_app_backend.Models.CoachQuestion", "CoachQuestion")
                        .WithMany()
                        .HasForeignKey("CoachQuestionId");

                    b.Navigation("CoachQuestion");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Coach.CoachCardNumber", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithOne("CoachCardNumber")
                        .HasForeignKey("sport_app_backend.Models.Account.Coach.CoachCardNumber", "CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.User", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithOne("User")
                        .HasForeignKey("sport_app_backend.Models.Account.User", "AthleteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithOne("User")
                        .HasForeignKey("sport_app_backend.Models.Account.User", "CoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Athlete");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("sport_app_backend.Models.Actions.Activity", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithMany("Activities")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("sport_app_backend.Models.Actions.CouchExercise.CoachPineExercise", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("sport_app_backend.Models.Actions.CouchExercise.LastWorkoutExercise", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Program.WorkoutProgram", "WorkoutProgram")
                        .WithMany()
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Coach");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("sport_app_backend.Models.AthleteChangePhoto", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany("AthleteChangePhotos")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("sport_app_backend.Models.Challenge_Achievement.Challenge", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("sport_app_backend.Models.Chat.ChatMessage", b =>
                {
                    b.HasOne("sport_app_backend.Models.Chat.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Account.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("sport_app_backend.Models.Chat.ConversationParticipant", b =>
                {
                    b.HasOne("sport_app_backend.Models.Chat.Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Account.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("sport_app_backend.Models.CoachQuestion", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("sport_app_backend.Models.NotificationSubscription", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.CoachPayout", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.DiscountCode", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany("DiscountCodes")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.DiscountCodeCoachService", b =>
                {
                    b.HasOne("sport_app_backend.Models.TrainingPlan.CoachService", "CoachService")
                        .WithMany("DiscountCodeCoachServices")
                        .HasForeignKey("CoachServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Payments.DiscountCode", "DiscountCode")
                        .WithMany("DiscountCodeCoachServices")
                        .HasForeignKey("DiscountCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoachService");

                    b.Navigation("DiscountCode");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.Payment", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithMany("Payments")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Question.A_Question.AthleteQuestion", "AthleteQuestion")
                        .WithMany()
                        .HasForeignKey("AthleteQuestionId");

                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany("Payments")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.TrainingPlan.CoachService", "CoachService")
                        .WithMany()
                        .HasForeignKey("CoachServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Payments.DiscountCode", "DiscountCode")
                        .WithMany("Payments")
                        .HasForeignKey("DiscountCodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Athlete");

                    b.Navigation("AthleteQuestion");

                    b.Navigation("Coach");

                    b.Navigation("CoachService");

                    b.Navigation("DiscountCode");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.PaymentAttempt", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.TrainingPlan.CoachService", "CoachService")
                        .WithMany()
                        .HasForeignKey("CoachServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Coach");

                    b.Navigation("CoachService");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.WalletTransaction", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.ExerciseChangeRequest", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Program.SingleExercise", "SingleExercise")
                        .WithMany()
                        .HasForeignKey("SingleExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Program.TrainingSession", "TrainingSession")
                        .WithMany()
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Coach");

                    b.Navigation("SingleExercise");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.ExerciseFeedback", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Program.SingleExercise", "SingleExercise")
                        .WithMany()
                        .HasForeignKey("SingleExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Program.TrainingSession", "TrainingSession")
                        .WithMany()
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Coach");

                    b.Navigation("SingleExercise");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.ProgramInDay", b =>
                {
                    b.HasOne("sport_app_backend.Models.Program.WorkoutProgram", "WorkoutProgram")
                        .WithMany("ProgramInDays")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.SingleExercise", b =>
                {
                    b.HasOne("sport_app_backend.Models.Actions.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Program.ProgramInDay", "ProgramInDay")
                        .WithMany("AllExerciseInDays")
                        .HasForeignKey("ProgramInDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("ProgramInDay");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.TrainingSession", b =>
                {
                    b.HasOne("sport_app_backend.Models.Program.ProgramInDay", "ProgramInDay")
                        .WithMany()
                        .HasForeignKey("ProgramInDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Program.WorkoutProgram", "WorkoutProgram")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramInDay");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgram", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithMany("WorkoutPrograms")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany("WorkoutPrograms")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Payments.Payment", "Payment")
                        .WithOne("WorkoutProgram")
                        .HasForeignKey("sport_app_backend.Models.Program.WorkoutProgram", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Coach");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgramFeedback", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", null)
                        .WithMany("WorkoutProgramFeedbacks")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Program.WorkoutProgram", "WorkoutProgram")
                        .WithOne("WorkoutProgramFeedback")
                        .HasForeignKey("sport_app_backend.Models.Program.WorkoutProgramFeedback", "WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgramTemplate.TemplateProgramInDay", b =>
                {
                    b.HasOne("sport_app_backend.Models.Program.WorkoutProgramTemplate.WorkoutProgramTemplate", "WorkoutProgramTemplate")
                        .WithMany("ProgramInDays")
                        .HasForeignKey("WorkoutProgramTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutProgramTemplate");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgramTemplate.TemplateSingleExercise", b =>
                {
                    b.HasOne("sport_app_backend.Models.Actions.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Program.WorkoutProgramTemplate.TemplateProgramInDay", "TemplateProgramInDay")
                        .WithMany("AllExerciseInDays")
                        .HasForeignKey("TemplateProgramInDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("TemplateProgramInDay");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgramTemplate.WorkoutProgramTemplate", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("sport_app_backend.Models.Question.A_Question.AthleteBodyImage", b =>
                {
                    b.HasOne("sport_app_backend.Models.Question.A_Question.AthleteQuestion", "AthleteQuestion")
                        .WithOne("AthleteBodyImage")
                        .HasForeignKey("sport_app_backend.Models.Question.A_Question.AthleteBodyImage", "AthleteQuestionId");

                    b.Navigation("AthleteQuestion");
                });

            modelBuilder.Entity("sport_app_backend.Models.Question.A_Question.AthleteQuestion", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithMany("AthleteQuestions")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("sport_app_backend.Models.Question.A_Question.InjuryArea", b =>
                {
                    b.HasOne("sport_app_backend.Models.Question.A_Question.AthleteQuestion", "AthleteQuestion")
                        .WithOne("InjuryArea")
                        .HasForeignKey("sport_app_backend.Models.Question.A_Question.InjuryArea", "AthleteQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AthleteQuestion");
                });

            modelBuilder.Entity("sport_app_backend.Models.Support.SupportTicket", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("sport_app_backend.Models.Support.TicketMessage", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.HasOne("sport_app_backend.Models.Support.SupportTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("sport_app_backend.Models.TrainingPlan.CoachService", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Coach.Coach", "Coach")
                        .WithMany("CoachingServices")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("sport_app_backend.Models.UserExternalAccount.UserExternalAccount", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.User", "User")
                        .WithMany("ExternalAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("sport_app_backend.Models.UserMessageStatus", b =>
                {
                    b.HasOne("sport_app_backend.Models.InAppMessage", "InAppMessage")
                        .WithMany()
                        .HasForeignKey("InAppMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Account.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InAppMessage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("sport_app_backend.Models.WaterInDay", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithMany("WaterInDays")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("sport_app_backend.Models.WaterInTake", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete.Athlete", "Athlete")
                        .WithOne("WaterInTake")
                        .HasForeignKey("sport_app_backend.Models.WaterInTake", "AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Athlete.Athlete", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("AthleteQuestions");

                    b.Navigation("Payments");

                    b.Navigation("User")
                        .IsRequired();

                    b.Navigation("WaterInDays");

                    b.Navigation("WaterInTake");

                    b.Navigation("WeightEntries");

                    b.Navigation("WorkoutPrograms");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Coach.Coach", b =>
                {
                    b.Navigation("AthleteChangePhotos");

                    b.Navigation("CoachCardNumber");

                    b.Navigation("CoachingServices");

                    b.Navigation("DiscountCodes");

                    b.Navigation("Payments");

                    b.Navigation("User")
                        .IsRequired();

                    b.Navigation("WorkoutProgramFeedbacks");

                    b.Navigation("WorkoutPrograms");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.User", b =>
                {
                    b.Navigation("ExternalAccounts");
                });

            modelBuilder.Entity("sport_app_backend.Models.Chat.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.DiscountCode", b =>
                {
                    b.Navigation("DiscountCodeCoachServices");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.Payment", b =>
                {
                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.ProgramInDay", b =>
                {
                    b.Navigation("AllExerciseInDays");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgram", b =>
                {
                    b.Navigation("ProgramInDays");

                    b.Navigation("TrainingSessions");

                    b.Navigation("WorkoutProgramFeedback");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgramTemplate.TemplateProgramInDay", b =>
                {
                    b.Navigation("AllExerciseInDays");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgramTemplate.WorkoutProgramTemplate", b =>
                {
                    b.Navigation("ProgramInDays");
                });

            modelBuilder.Entity("sport_app_backend.Models.Question.A_Question.AthleteQuestion", b =>
                {
                    b.Navigation("AthleteBodyImage");

                    b.Navigation("InjuryArea");
                });

            modelBuilder.Entity("sport_app_backend.Models.Support.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("sport_app_backend.Models.TrainingPlan.CoachService", b =>
                {
                    b.Navigation("DiscountCodeCoachServices");
                });
#pragma warning restore 612, 618
        }
    }
}
