// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sport_app_backend.Data;

#nullable disable

namespace sport_app_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("sport_app_backend.Models.Account.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("CurrentWeight")
                        .HasColumnType("double");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RestTime")
                        .HasColumnType("int");

                    b.Property<int>("TimeBeforeWorkout")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("WeightGoal")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CoachQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Domain")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("HeadLine")
                        .IsRequired()
                        .HasMaxLength(124)
                        .HasColumnType("varchar(124)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StartCoachingYear")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoachQuestionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.CoachService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("CommunicateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("HaveSupport")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NumberOfSell")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("CoachServices");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImageProfile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("RefreshTokeNExpire")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<int>("TypeOfUser")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.WeightEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CurrentDate")
                        .HasColumnType("date");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("WeightEntries");
                });

            modelBuilder.Entity("sport_app_backend.Models.Actions.Activitie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActivityCategory")
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<double>("CaloriesLost")
                        .HasColumnType("double");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Distance")
                        .HasColumnType("double");

                    b.Property<double>("Duration")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("sport_app_backend.Models.Actions.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BaseCategory")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExerciseCategories")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ExerciseLevel")
                        .HasColumnType("int");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Locations")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TargetMuscles")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("VideoLink")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("sport_app_backend.Models.Challenge_Achievement.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("ChallengeType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("sport_app_backend.Models.CoachQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("DifficultTrackAthletes")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Disciplines")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("HardCommunicationWithAthletes")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("ManagingRevenue")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Motivations")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PresentsPracticeProgram")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TrackAthlete")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("WorkOnlineWithAthletes")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CoachQuestions");
                });

            modelBuilder.Entity("sport_app_backend.Models.Login_Sinup.CodeVerify", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("TimeCodeSend")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CodeVerifies");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("AthleteQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("CoachServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("AthleteQuestionId");

                    b.HasIndex("CoachId");

                    b.HasIndex("CoachServiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.ProgramInDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ForWhichDay")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutProgramId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("ProgramInDays");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.SingleExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramInDayId")
                        .HasColumnType("int");

                    b.Property<int>("Rep")
                        .HasColumnType("int");

                    b.Property<int>("Set")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ProgramInDayId");

                    b.ToTable("SingleExercises");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("DedicatedWarmUp")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GeneralWarmUp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("ProgramDuration")
                        .HasColumnType("int");

                    b.Property<string>("ProgramLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProgramPriorities")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("CoachId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.ToTable("WorkoutPrograms");
                });

            modelBuilder.Entity("sport_app_backend.Models.Question.A_Question.AthleteQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<int>("CurrentBodyForm")
                        .HasColumnType("int");

                    b.Property<int>("DaysPerWeekToExercise")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseGoal")
                        .HasColumnType("int");

                    b.Property<int?>("FitnessLevel")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("AthleteQuestions");
                });

            modelBuilder.Entity("sport_app_backend.Models.Question.A_Question.InjuryArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("HormonalAndGlandular")
                        .HasColumnType("longtext");

                    b.Property<string>("InternalAndDigestive")
                        .HasColumnType("longtext");

                    b.Property<bool>("None")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Others")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Skeletal")
                        .HasColumnType("longtext");

                    b.Property<string>("SoftTissueAndLigament")
                        .HasColumnType("longtext");

                    b.Property<string>("Specific")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AthleteQuestionId")
                        .IsUnique();

                    b.ToTable("InjuryAreas");
                });

            modelBuilder.Entity("sport_app_backend.Models.ReportApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ReportApps");
                });

            modelBuilder.Entity("sport_app_backend.Models.WaterInDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("NumberOfCupsDrinked")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.ToTable("WaterInDays");
                });

            modelBuilder.Entity("sport_app_backend.Models.WaterInTake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AthleteId")
                        .HasColumnType("int");

                    b.Property<int>("DailyCupOfWater")
                        .HasColumnType("int");

                    b.Property<int>("Reminder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId")
                        .IsUnique();

                    b.ToTable("WaterInTakes");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Athlete", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.User", "User")
                        .WithOne("Athlete")
                        .HasForeignKey("sport_app_backend.Models.Account.Athlete", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Coach", b =>
                {
                    b.HasOne("sport_app_backend.Models.CoachQuestion", "CoachQuestion")
                        .WithMany()
                        .HasForeignKey("CoachQuestionId");

                    b.HasOne("sport_app_backend.Models.Account.User", "User")
                        .WithOne("Coach")
                        .HasForeignKey("sport_app_backend.Models.Account.Coach", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoachQuestion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.CoachService", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Coach", "Coach")
                        .WithMany("CoachingServices")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.WeightEntry", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete", "Athlete")
                        .WithMany("WeightEntries")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("sport_app_backend.Models.Actions.Activitie", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("sport_app_backend.Models.Challenge_Achievement.Challenge", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("sport_app_backend.Models.CoachQuestion", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.Payment", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete", "Athlete")
                        .WithMany("Payments")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Question.A_Question.AthleteQuestion", "AthleteQuestion")
                        .WithMany()
                        .HasForeignKey("AthleteQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Account.Coach", "Coach")
                        .WithMany("Payments")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Account.CoachService", "CoachService")
                        .WithMany()
                        .HasForeignKey("CoachServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("AthleteQuestion");

                    b.Navigation("Coach");

                    b.Navigation("CoachService");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.ProgramInDay", b =>
                {
                    b.HasOne("sport_app_backend.Models.Program.WorkoutProgram", "WorkoutProgram")
                        .WithMany("ProgramInDays")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.SingleExercise", b =>
                {
                    b.HasOne("sport_app_backend.Models.Actions.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Program.ProgramInDay", "ProgramInDay")
                        .WithMany("AllExerciseInDays")
                        .HasForeignKey("ProgramInDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("ProgramInDay");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgram", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete", "Athlete")
                        .WithMany("WorkoutPrograms")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Account.Coach", "Coach")
                        .WithMany("WorkoutPrograms")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sport_app_backend.Models.Payments.Payment", "Payment")
                        .WithOne("WorkoutProgram")
                        .HasForeignKey("sport_app_backend.Models.Program.WorkoutProgram", "PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Coach");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("sport_app_backend.Models.Question.A_Question.AthleteQuestion", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete", "Athlete")
                        .WithMany("AthleteQuestions")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("sport_app_backend.Models.Question.A_Question.InjuryArea", b =>
                {
                    b.HasOne("sport_app_backend.Models.Question.A_Question.AthleteQuestion", "AthleteQuestion")
                        .WithOne("InjuryArea")
                        .HasForeignKey("sport_app_backend.Models.Question.A_Question.InjuryArea", "AthleteQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AthleteQuestion");
                });

            modelBuilder.Entity("sport_app_backend.Models.ReportApp", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("sport_app_backend.Models.WaterInDay", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete", "Athlete")
                        .WithMany("WaterInDays")
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("sport_app_backend.Models.WaterInTake", b =>
                {
                    b.HasOne("sport_app_backend.Models.Account.Athlete", "Athlete")
                        .WithOne("WaterInTake")
                        .HasForeignKey("sport_app_backend.Models.WaterInTake", "AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Athlete", b =>
                {
                    b.Navigation("AthleteQuestions");

                    b.Navigation("Payments");

                    b.Navigation("WaterInDays");

                    b.Navigation("WaterInTake");

                    b.Navigation("WeightEntries");

                    b.Navigation("WorkoutPrograms");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.Coach", b =>
                {
                    b.Navigation("CoachingServices");

                    b.Navigation("Payments");

                    b.Navigation("WorkoutPrograms");
                });

            modelBuilder.Entity("sport_app_backend.Models.Account.User", b =>
                {
                    b.Navigation("Athlete");

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("sport_app_backend.Models.Payments.Payment", b =>
                {
                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.ProgramInDay", b =>
                {
                    b.Navigation("AllExerciseInDays");
                });

            modelBuilder.Entity("sport_app_backend.Models.Program.WorkoutProgram", b =>
                {
                    b.Navigation("ProgramInDays");
                });

            modelBuilder.Entity("sport_app_backend.Models.Question.A_Question.AthleteQuestion", b =>
                {
                    b.Navigation("InjuryArea");
                });
#pragma warning restore 612, 618
        }
    }
}
