name: Docker CI/CD ASP.NET

on:
  push:
    branches:
      - stagingMain
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set environment variables
        id: env
        run: |
          if [[ "${GITHUB_REF##*/}" == "stagingMain" ]]; then
            echo "ENV=staging" >> $GITHUB_ENV
            echo "PORT=8080" >> $GITHUB_ENV
            echo "CONTAINER=sport-staging-backend" >> $GITHUB_ENV
          else
            echo "ENV=production" >> $GITHUB_ENV
            echo "PORT=8081" >> $GITHUB_ENV
            echo "CONTAINER=sport-prod-backend" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: docker build -t $CONTAINER:latest .

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop $CONTAINER || true
            docker rm $CONTAINER || true

            docker run -d \
              --name $CONTAINER \
              -p $PORT:8080 \
              -e ASPNETCORE_ENVIRONMENT=$ENV \
              -e ConnectionStrings__DefaultConnection="${{ secrets[ env.ENV == 'staging' && 'STAGING_ConnectionStrings__DefaultConnection' || 'PROD_ConnectionStrings__DefaultConnection' ] }}" \
              -e Zarinpal__MerchantId="${{ secrets[ env.ENV == 'staging' && 'STAGING_Zarinpal__MerchantId' || 'PROD_Zarinpal__MerchantId' ] }}" \
              -e Liara__accessKey="${{ secrets[ env.ENV == 'staging' && 'STAGING_Liara__accessKey' || 'PROD_Liara__accessKey' ] }}" \
              -e Liara__secretKey="${{ secrets[ env.ENV == 'staging' && 'STAGING_Liara__secretKey' || 'PROD_Liara__secretKey' ] }}" \
              -e JWT__SigningKey="${{ secrets[ env.ENV == 'staging' && 'STAGING_JWT__SigningKey' || 'PROD_JWT__SigningKey' ] }}" \
              -e SMS__accessKey="${{ secrets[ env.ENV == 'staging' && 'STAGING_SMS__accessKey' || 'PROD_SMS__accessKey' ] }}" \
              -e Liara__endpoint="${{ secrets[ env.ENV == 'staging' && 'STAGING_Liara__endpoint' || 'PROD_Liara__endpoint' ] }}" \
              -e Liara__BucketName="${{ secrets[ env.ENV == 'staging' && 'STAGING_Liara__BucketName' || 'PROD_Liara__BucketName' ] }}" \
              -e Zarinpal__endpoint="${{ secrets[ env.ENV == 'staging' && 'STAGING_Zarinpal__endpoint' || 'PROD_Zarinpal__endpoint' ] }}" \
              -e AllowedIps__0="${{ secrets[ env.ENV == 'staging' && 'STAGING_AllowedIps__0' || 'PROD_AllowedIps__0' ] }}" \
              $CONTAINER:latest

